version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}

volumes:
  pgdata:
