default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: loftwah_dashboard_development
